[search]
base_path = D:\DANE
min_attachment_size = 51200
recursive_search = True
save_metadata = True

[keywords]
list = umowa,podwykonaw,aneks,zlecenie,kontrakt,draft,wniosek,wdr,faktura,protokol,zamowienie,sprawozdanie,pozwolenie,decyzja

[imap]
; host = imap.gmail.com
; port = 993
; user = twoj@email.pl
; password = twoje-haslo-aplikacji
; folder = INBOX
; date_from = 2026-02-01
; date_to =
